import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'transaction_model.dart';

/// IsarService is the single entry point for all database operations.
///
/// Usage pattern:
///   final service = IsarService();
///   await service.saveTransaction(myRecord);
///   final all = await service.getAllTransactions();
class IsarService {
  /// The Isar instance — kept private so only this service touches the DB
  late Future<Isar> db;

  /// Constructor: immediately kicks off the database opening process
  IsarService() {
    db = openDB();
  }

  // ─────────────────────────────────────────────
  // OPEN DATABASE
  // ─────────────────────────────────────────────

  /// Opens (or reuses) the local Isar database.
  /// [getApplicationDocumentsDirectory] is a Flutter helper that finds the
  /// correct local storage folder on both Android and iOS.
  Future<Isar> openDB() async {
    // If the database is already open (e.g., hot reload), reuse it
    if (Isar.instanceNames.isEmpty) {
      final dir = await getApplicationDocumentsDirectory();

      return await Isar.open(
        [TransactionRecordSchema], // generated by build_runner in Step 3
        directory: dir.path,
        inspector: true, // lets you inspect DB in Isar Inspector (dev tool)
      );
    }

    // Return the already-open instance
    return Future.value(Isar.getInstance());
  }

  // ─────────────────────────────────────────────
  // SAVE (CREATE / UPDATE)
  // ─────────────────────────────────────────────

  /// Saves a new transaction record to the database.
  /// If the record already has an id, it will update (upsert) it.
  Future<void> saveTransaction(TransactionRecord record) async {
    final isar = await db;
    // writeTxn = write transaction (required for any data change)
    await isar.writeTxn(() async {
      await isar.transactionRecords.put(record);
    });
  }

  // ─────────────────────────────────────────────
  // READ ALL
  // ─────────────────────────────────────────────

  /// Returns all saved transactions, newest first.
  Future<List<TransactionRecord>> getAllTransactions() async {
    final isar = await db;
    return await isar.transactionRecords
        .where()
        .sortByTimestampDesc() // newest first
        .findAll();
  }

  // ─────────────────────────────────────────────
  // REAL-TIME STREAM
  // ─────────────────────────────────────────────

  /// Returns a Stream that emits the full list every time a transaction
  /// is added, updated, or deleted. Use with StreamBuilder in your UI.
  ///
  /// Example:
  ///   StreamBuilder<List<TransactionRecord>>(
  ///     stream: isarService.listenToTransactions(),
  ///     builder: (context, snapshot) { ... }
  ///   )
  Stream<List<TransactionRecord>> listenToTransactions() async* {
    final isar = await db;
    yield* isar.transactionRecords
        .where()
        .sortByTimestampDesc()
        .watch(fireImmediately: true); // emits current data right away
  }

  // ─────────────────────────────────────────────
  // DELETE ONE
  // ─────────────────────────────────────────────

  /// Deletes a single transaction by its ID.
  Future<void> deleteTransaction(int id) async {
    final isar = await db;
    await isar.writeTxn(() async {
      await isar.transactionRecords.delete(id);
    });
  }

  // ─────────────────────────────────────────────
  // DELETE ALL
  // ─────────────────────────────────────────────

  /// ⚠️ Deletes EVERY transaction record. Use with caution!
  Future<void> clearAllTransactions() async {
    final isar = await db;
    await isar.writeTxn(() async {
      await isar.transactionRecords.clear();
    });
  }
}
