import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'transaction_model.dart';
import 'fee_model.dart';
import '../services/receipt_parser.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// IsarService is the single entry point for all database operations.
///
/// Usage pattern:
///   final service = IsarService();
///   await service.saveTransaction(myRecord);
///   final all = await service.getAllTransactions();
class IsarService {
  /// The Isar instance — kept private so only this service touches the DB
  late Future<Isar> db;

  /// Constructor: immediately kicks off the database opening process
  IsarService() {
    db = openDB();
  }

  // ─────────────────────────────────────────────
  // OPEN DATABASE
  // ─────────────────────────────────────────────

  /// Opens (or reuses) the local Isar database.
  /// [getApplicationDocumentsDirectory] is a Flutter helper that finds the
  /// correct local storage folder on both Android and iOS.
  Future<Isar> openDB() async {
    Isar isar;
    if (Isar.instanceNames.isEmpty) {
      final dir = await getApplicationDocumentsDirectory();

      isar = await Isar.open(
        [TransactionRecordSchema, FeeRangeSchema], // generated by build_runner in Step 3
        directory: dir.path,
        inspector: true, // lets you inspect DB in Isar Inspector (dev tool)
      );

      // Seed or reset fee ranges if count is not 15 (ensures Nanay gets exactly the correct 15 ranges)
      if (await isar.feeRanges.count() != 15) {
        await isar.writeTxn(() async {
          await isar.feeRanges.clear();
          await isar.feeRanges.putAll([
            FeeRange()..minAmount = 1..maxAmount = 1000..fee = 15,
            FeeRange()..minAmount = 1001..maxAmount = 2000..fee = 20,
            FeeRange()..minAmount = 2001..maxAmount = 3000..fee = 30,
            FeeRange()..minAmount = 3001..maxAmount = 4000..fee = 40,
            FeeRange()..minAmount = 4001..maxAmount = 5000..fee = 50,
            FeeRange()..minAmount = 5001..maxAmount = 6000..fee = 60,
            FeeRange()..minAmount = 6001..maxAmount = 7000..fee = 70,
            FeeRange()..minAmount = 7001..maxAmount = 8000..fee = 80,
            FeeRange()..minAmount = 8001..maxAmount = 9000..fee = 90,
            FeeRange()..minAmount = 9001..maxAmount = 10000..fee = 100,
            FeeRange()..minAmount = 10001..maxAmount = 11000..fee = 110,
            FeeRange()..minAmount = 11001..maxAmount = 12000..fee = 120,
            FeeRange()..minAmount = 12001..maxAmount = 13000..fee = 130,
            FeeRange()..minAmount = 13001..maxAmount = 14000..fee = 140,
            FeeRange()..minAmount = 14001..maxAmount = 15000..fee = 150,
          ]);
        });
      }
    } else {
      isar = Isar.getInstance()!;
    }

    // Run the retroactive sync every time the database is initialized or hot-restarted
    await _syncHistoricalNames(isar);

    return isar;
  }

  /// Helper to normalize phone numbers (extracts the last 9 digits to ignore spaces, country codes, etc.)
  String _normalizePhone(String? phone) {
    if (phone == null) return '';
    final digits = phone.replaceAll(RegExp(r'[^\d]'), '');
    if (digits.length >= 9) {
      return digits.substring(digits.length - 9);
    }
    return digits;
  }

  /// Retroactive name sync to maintain database consistency
  Future<void> _syncHistoricalNames(Isar isar) async {
    final allTx = await isar.transactionRecords.where().findAll();
    final phoneToLatestName = <String, MapEntry<String, DateTime>>{};
    
    for (final tx in allTx) {
      final rawPhone = tx.senderNumber?.trim();
      final phone = _normalizePhone(rawPhone);
      final name = tx.senderName?.trim();
      
      if (phone.isNotEmpty && name != null && name.isNotEmpty) {
        final timestamp = tx.timestamp;
        final existing = phoneToLatestName[phone];
        if (existing == null || timestamp.isAfter(existing.value)) {
          phoneToLatestName[phone] = MapEntry(name, timestamp);
        }
      }
    }
    
    final toUpdate = <TransactionRecord>[];
    for (final tx in allTx) {
      final rawPhone = tx.senderNumber?.trim();
      final phone = _normalizePhone(rawPhone);
      if (phone.isNotEmpty) {
        final latest = phoneToLatestName[phone];
        if (latest != null && tx.senderName != latest.key) {
          tx.senderName = latest.key;
          toUpdate.add(tx);
        }
      }
    }
    
    if (toUpdate.isNotEmpty) {
      await isar.writeTxn(() async {
        await isar.transactionRecords.putAll(toUpdate);
      });
    }
  }

  // ─────────────────────────────────────────────
  // SAVE (CREATE / UPDATE)
  // ─────────────────────────────────────────────

  /// Saves a new transaction record to the database.
  /// If the record already has an id, it will update (upsert) it.
  /// Automatically searches all other records with the same contact number
  /// and updates their recipient name to ensure absolute data consistency.
  Future<void> saveTransaction(TransactionRecord record) async {
    final isar = await db;
    // Auto-populate recordedAt timestamp on create if not already set
    record.recordedAt ??= DateTime.now();
    
    // writeTxn = write transaction (required for any data change)
    await isar.writeTxn(() async {
      // 1. Save the target transaction
      await isar.transactionRecords.put(record);

      // 2. Query and sync all other entries sharing the exact same phone number (normalized)
      final rawPhone = record.senderNumber?.trim();
      final phone = _normalizePhone(rawPhone);
      final name = record.senderName?.trim();
      
      if (phone.isNotEmpty && name != null && name.isNotEmpty) {
        final allMatches = await isar.transactionRecords.where().findAll();
        final matches = allMatches.where((tx) => 
          tx.id != record.id && _normalizePhone(tx.senderNumber?.trim()) == phone
        ).toList();

        if (matches.isNotEmpty) {
          for (final tx in matches) {
            tx.senderName = name;
          }
          // Bulk put updated records back into the DB
          await isar.transactionRecords.putAll(matches);
        }
      }
    });
  }

  // ─────────────────────────────────────────────
  // READ ALL
  // ─────────────────────────────────────────────

  /// Returns all saved transactions, newest first.
  Future<List<TransactionRecord>> getAllTransactions() async {
    final isar = await db;
    return await isar.transactionRecords
        .where()
        .sortByTimestampDesc() // newest first
        .findAll();
  }

  // ─────────────────────────────────────────────
  // REAL-TIME STREAM
  // ─────────────────────────────────────────────

  /// Returns a Stream that emits the full list every time a transaction
  /// is added, updated, or deleted. Use with StreamBuilder in your UI.
  ///
  /// Example:
  /// ```dart
  /// StreamBuilder<List<TransactionRecord>>(
  ///   stream: isarService.listenToTransactions(),
  ///   builder: (context, snapshot) { ... }
  /// )
  /// ```
  Stream<List<TransactionRecord>> listenToTransactions() async* {
    final isar = await db;
    yield* isar.transactionRecords
        .where()
        .sortByTimestampDesc()
        .watch(fireImmediately: true); // emits current data right away
  }

  // ─────────────────────────────────────────────
  // DELETE ONE
  // ─────────────────────────────────────────────

  /// Deletes a single transaction by its ID.
  Future<void> deleteTransaction(int id) async {
    final isar = await db;
    await isar.writeTxn(() async {
      await isar.transactionRecords.delete(id);
    });
  }

  // ─────────────────────────────────────────────
  // DELETE ALL
  // ─────────────────────────────────────────────

  /// ⚠️ Deletes EVERY transaction record. Use with caution!
  Future<void> clearAllTransactions() async {
    final isar = await db;
    await isar.writeTxn(() async {
      await isar.transactionRecords.clear();
    });
  }

  // ─────────────────────────────────────────────
  // SAVE FROM PARSED RECEIPT
  // ─────────────────────────────────────────────

  /// Convenience method: builds a [TransactionRecord] from a [ParsedReceipt]
  /// and saves it. Falls back to sensible defaults for any null fields.
  Future<void> saveFromParsedReceipt(ParsedReceipt receipt, {double? manualFee}) async {
    final record = TransactionRecord()
      ..platform         = receipt.platform
      ..transactionType  = receipt.transactionType
      ..amount           = receipt.amount ?? 0.0
      ..referenceNumber  = receipt.referenceNumber ?? 'UNKNOWN'
      ..timestamp        = receipt.transactionDate ?? DateTime.now()
      ..senderName       = receipt.personName
      ..senderNumber     = receipt.phoneNumber
      ..remainingBalance = receipt.remainingBalance
      ..fee              = manualFee ?? await calculateFeeForAmount(receipt.amount ?? 0.0);
    await saveTransaction(record);
  }

  // ─────────────────────────────────────────────
  // FEE RANGES (CRUD)
  // ─────────────────────────────────────────────

  /// Get all configured fee ranges, sorted by minAmount
  Future<List<FeeRange>> getAllFeeRanges() async {
    final isar = await db;
    return await isar.feeRanges.where().sortByMinAmount().findAll();
  }

  /// Add or update a fee range
  Future<void> saveFeeRange(FeeRange range) async {
    final isar = await db;
    await isar.writeTxn(() async {
      await isar.feeRanges.put(range);
    });
  }

  /// Delete a fee range
  Future<void> deleteFeeRange(int id) async {
    final isar = await db;
    await isar.writeTxn(() async {
      await isar.feeRanges.delete(id);
    });
  }

  /// Computes the fee for a given amount by checking the configured ranges
  /// If it exceeds the standard maximum threshold, a pro-rata fee rule is applied.
  Future<double?> calculateFeeForAmount(double amount) async {
    final isar = await db;
    
    // Load setting boundaries from SharedPreferences
    final prefs = await SharedPreferences.getInstance();
    final threshold = prefs.getDouble('fee_max_threshold') ?? 15000.0;
    final rate = prefs.getDouble('fee_pro_rata_rate') ?? 10.0;

    if (amount >= threshold) {
      // Pro-rata rule: e.g. ₱10 per ₱1,000
      return (amount / 1000.0) * rate;
    }

    final ranges = await isar.feeRanges.where().findAll();
    for (final range in ranges) {
      if (amount >= range.minAmount && amount <= range.maxAmount) {
        return range.fee;
      }
    }
    return null; // No fee range matches
  }
}
